version: '3'

networks:
  ln:

services:

  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xyzw1234
    volumes:
      - .\postgresql\entrypoint\:/docker-entrypoint-initdb.d/
    networks:
      - ln